const dummyText = [
  " Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Imperdiet dui accumsan sit amet nulla. Pulvinar etiam non quam lacus suspendisse faucibus interdum posuere lorem. Vitae justo eget magna fermentum. Amet luctus venenatis lectus magna fringilla. Volutpat odio facilisis mauris sit amet massa. Elit eget gravida cum sociis. Odio aenean sed adipiscing diam donec adipiscing tristique risus nec. Porttitor rhoncus dolor purus non enim praesent elementum facilisis. Id eu nisl nunc mi ipsum faucibus vitae.",

  "Senectus et netus et malesuada fames ac turpis egestas integer. Pretium quam vulputate dignissim suspendisse in est. Elit at imperdiet dui accumsan sit amet. Morbi tincidunt augue interdum velit euismod in pellentesque massa. Purus faucibus ornare suspendisse sed. Ornare aenean euismod elementum nisi quis. Vitae semper quis lectus nulla at volutpat. Massa enim nec dui nunc mattis enim ut tellus. Faucibus purus in massa tempor nec feugiat nisl pretium fusce. Sagittis vitae et leo duis ut. Vitae elementum curabitur vitae nunc sed velit dignissim sodales. Venenatis urna cursus eget nunc scelerisque viverra. Integer vitae justo eget magna fermentum iaculis eu non. Tortor aliquam nulla facilisi cras. Nunc sed augue lacus viverra vitae congue.",

  "Eu augue ut lectus arcu bibendum at varius. Feugiat sed lectus vestibulum mattis ullamcorper velit sed. Posuere ac ut consequat semper viverra. Maecenas pharetra convallis posuere morbi leo urna. Tristique risus nec feugiat in fermentum posuere. Leo integer malesuada nunc vel risus. Quam adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus. Nisl purus in mollis nunc. Morbi tristique senectus et netus et. Ac turpis egestas sed tempus urna et pharetra pharetra massa. Purus sit amet volutpat consequat mauris nunc congue nisi vitae. Tempus urna et pharetra pharetra massa. Ut diam quam nulla porttitor massa. In mollis nunc sed id. Placerat duis ultricies lacus sed turpis tincidunt id aliquet. Eget mi proin sed libero enim sed faucibus turpis in. Egestas fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate sapien. Leo a diam sollicitudin tempor id eu nisl nunc mi. Tellus integer feugiat scelerisque varius morbi enim nunc faucibus. Gravida dictum fusce ut placerat.",

  "Magna fringilla urna porttitor rhoncus. Quam viverra orci sagittis eu volutpat odio facilisis. Vestibulum mattis ullamcorper velit sed ullamcorper morbi. Eget nulla facilisi etiam dignissim diam quis. Pellentesque habitant morbi tristique senectus. Fermentum et sollicitudin ac orci. Amet justo donec enim diam. Augue interdum velit euismod in pellentesque massa. A diam sollicitudin tempor id eu nisl nunc mi ipsum. Egestas congue quisque egestas diam in arcu. Pellentesque massa placerat duis ultricies lacus sed. Amet consectetur adipiscing elit pellentesque habitant morbi tristique senectus et. Cras adipiscing enim eu turpis egestas pretium aenean pharetra. Neque vitae tempus quam pellentesque nec nam aliquam. Sed sed risus pretium quam vulputate dignissim. Diam ut venenatis tellus in. Facilisis magna etiam tempor orci. Tellus cras adipiscing enim eu turpis egestas pretium aenean pharetra.",

  "Urna molestie at elementum eu facilisis sed. Quam id leo in vitae turpis massa sed. Eu facilisis sed odio morbi quis. Imperdiet sed euismod nisi porta lorem mollis aliquam ut. Mattis rhoncus urna neque viverra justo nec ultrices dui sapien. Consectetur purus ut faucibus pulvinar elementum. Tempus imperdiet nulla malesuada pellentesque elit eget. Lectus mauris ultrices eros in cursus. Nulla facilisi cras fermentum odio. Diam sollicitudin tempor id eu nisl nunc.",

  "Porttitor massa id neque aliquam vestibulum morbi. Tellus integer feugiat scelerisque varius morbi enim nunc faucibus. Vestibulum mattis ullamcorper velit sed ullamcorper morbi. Feugiat scelerisque varius morbi enim. Mi ipsum faucibus vitae aliquet. Orci phasellus egestas tellus rutrum tellus pellentesque eu tincidunt tortor. Pellentesque elit ullamcorper dignissim cras. In mollis nunc sed id semper risus in hendrerit gravida. Elementum eu facilisis sed odio morbi. Eu sem integer vitae justo eget. Amet mauris commodo quis imperdiet massa tincidunt nunc pulvinar. Dictum non consectetur a erat nam at. Id ornare arcu odio ut sem nulla pharetra diam sit.",

  "Venenatis tellus in metus vulputate eu scelerisque felis. Vel eros donec ac odio tempor orci dapibus ultrices. Eu non diam phasellus vestibulum. Iaculis eu non diam phasellus vestibulum lorem. Urna et pharetra pharetra massa massa ultricies. Nunc aliquet bibendum enim facilisis gravida neque. Neque ornare aenean euismod elementum nisi quis eleifend quam adipiscing. Nulla pellentesque dignissim enim sit amet. Nulla facilisi nullam vehicula ipsum a. Vitae et leo duis ut diam quam nulla. Sit amet nisl purus in mollis nunc sed. Molestie a iaculis at erat pellentesque adipiscing commodo elit at. Vestibulum lorem sed risus ultricies.",

  "Mattis vulputate enim nulla aliquet porttitor lacus luctus accumsan. Mauris in aliquam sem fringilla ut morbi tincidunt augue. Tortor id aliquet lectus proin. Ornare arcu dui vivamus arcu felis bibendum. Dictum non consectetur a erat nam at lectus urna duis. Urna nec tincidunt praesent semper feugiat nibh sed. A pellentesque sit amet porttitor eget dolor. In iaculis nunc sed augue lacus viverra vitae congue. Vivamus arcu felis bibendum ut. Tortor condimentum lacinia quis vel eros donec ac odio. Nec nam aliquam sem et tortor. Luctus venenatis lectus magna fringilla urna porttitor rhoncus. A scelerisque purus semper eget duis at tellus. Dui vivamus arcu felis bibendum ut tristique et egestas quis. Eu tincidunt tortor aliquam nulla facilisi cras fermentum. Scelerisque varius morbi enim nunc faucibus.",

  "Pellentesque sit amet porttitor eget dolor morbi non arcu. Ultrices neque ornare aenean euismod elementum nisi quis eleifend. In fermentum posuere urna nec tincidunt praesent. Lectus magna fringilla urna porttitor rhoncus dolor. Et magnis dis parturient montes nascetur ridiculus mus mauris vitae. Quis ipsum suspendisse ultrices gravida dictum. Sed risus pretium quam vulputate dignissim suspendisse. Vestibulum mattis ullamcorper velit sed ullamcorper morbi. Porttitor eget dolor morbi non arcu risus. At tellus at urna condimentum mattis pellentesque. Odio morbi quis commodo odio. Est sit amet facilisis magna etiam tempor orci. Morbi quis commodo odio aenean sed adipiscing diam donec adipiscing. Semper feugiat nibh sed pulvinar proin. Morbi tristique senectus et netus et malesuada.",

  "Posuere urna nec tincidunt praesent semper feugiat nibh sed. Aliquet risus feugiat in ante. Vulputate mi sit amet mauris commodo quis. Consectetur lorem donec massa sapien faucibus et molestie ac feugiat. Sagittis aliquam malesuada bibendum arcu vitae elementum. Diam quis enim lobortis scelerisque fermentum dui faucibus in ornare. Arcu dictum varius duis at consectetur. Bibendum neque egestas congue quisque egestas diam in arcu cursus. Elementum tempus egestas sed sed risus pretium quam vulputate. Proin gravida hendrerit lectus a. Nec dui nunc mattis enim ut tellus elementum. Viverra suspendisse potenti nullam ac tortor vitae purus. Porttitor eget dolor morbi non arcu. Condimentum id venenatis a condimentum vitae. Ultricies mi eget mauris pharetra. Massa placerat duis ultricies lacus sed turpis tincidunt. Sed sed risus pretium quam vulputate dignissim. Maecenas ultricies mi eget mauris pharetra et ultrices. Diam sit amet nisl suscipit adipiscing bibendum est. Et malesuada fames ac turpis egestas maecenas pharetra convallis.",

  "Imperdiet dui accumsan sit amet nulla facilisi. Aliquam ut porttitor leo a diam sollicitudin tempor id. Elementum tempus egestas sed sed risus. Tempor id eu nisl nunc mi ipsum faucibus vitae. Rhoncus urna neque viverra justo. Risus commodo viverra maecenas accumsan lacus vel facilisis. Neque gravida in fermentum et sollicitudin ac orci phasellus egestas. Justo nec ultrices dui sapien eget mi. Varius sit amet mattis vulputate. Duis at consectetur lorem donec massa.",

  "Cras fermentum odio eu feugiat. Risus feugiat in ante metus dictum. At consectetur lorem donec massa sapien faucibus et. Vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant. Blandit turpis cursus in hac habitasse platea dictumst quisque. Ut consequat semper viverra nam libero justo laoreet sit amet. Lobortis elementum nibh tellus molestie. Id volutpat lacus laoreet non curabitur gravida arcu ac tortor. Mi ipsum faucibus vitae aliquet nec ullamcorper sit amet risus. Molestie a iaculis at erat pellentesque adipiscing commodo. Volutpat sed cras ornare arcu. Suspendisse in est ante in nibh. Nulla at volutpat diam ut. Dignissim diam quis enim lobortis scelerisque. Diam maecenas ultricies mi eget mauris pharetra et ultrices neque. Ipsum suspendisse ultrices gravida dictum fusce ut. Sit amet facilisis magna etiam tempor orci eu lobortis elementum. Sit amet purus gravida quis blandit. Varius morbi enim nunc faucibus a pellentesque sit amet. Faucibus nisl tincidunt eget nullam.",

  "Blandit aliquam etiam erat velit scelerisque in dictum non consectetur. Enim eu turpis egestas pretium aenean pharetra. Cursus mattis molestie a iaculis at erat pellentesque. Nunc sed augue lacus viverra vitae congue eu consequat ac. Etiam dignissim diam quis enim lobortis scelerisque. Arcu cursus vitae congue mauris rhoncus aenean vel elit. Rutrum quisque non tellus orci ac auctor. Euismod quis viverra nibh cras pulvinar mattis nunc sed blandit. In nisl nisi scelerisque eu. Sed nisi lacus sed viverra tellus in hac habitasse. Vel risus commodo viverra maecenas.",

  "Molestie ac feugiat sed lectus. Eget arcu dictum varius duis at consectetur. Tempor orci eu lobortis elementum nibh tellus. Eget sit amet tellus cras adipiscing enim. Augue interdum velit euismod in pellentesque. Sed velit dignissim sodales ut eu sem integer vitae. Scelerisque varius morbi enim nunc faucibus. Sagittis purus sit amet volutpat consequat mauris nunc congue. Turpis in eu mi bibendum. Mauris rhoncus aenean vel elit scelerisque mauris pellentesque. Cursus metus aliquam eleifend mi in. Diam quam nulla porttitor massa id. Pellentesque pulvinar pellentesque habitant morbi tristique senectus et. Interdum velit laoreet id donec. Vel turpis nunc eget lorem dolor sed viverra ipsum.",

  "Pharetra convallis posuere morbi leo urna molestie at elementum eu. Sit amet venenatis urna cursus eget nunc scelerisque viverra mauris. Imperdiet dui accumsan sit amet nulla facilisi morbi. Mi in nulla posuere sollicitudin aliquam ultrices. Lacus sed turpis tincidunt id aliquet risus feugiat in. Sapien pellentesque habitant morbi tristique senectus et netus. Integer feugiat scelerisque varius morbi enim nunc faucibus a pellentesque. Id venenatis a condimentum vitae sapien pellentesque habitant morbi. Euismod lacinia at quis risus. Enim blandit volutpat maecenas volutpat blandit aliquam.",

  "Feugiat vivamus at augue eget. Morbi quis commodo odio aenean sed adipiscing diam donec. Elit pellentesque habitant morbi tristique senectus et. Ut diam quam nulla porttitor massa. Malesuada nunc vel risus commodo viverra maecenas accumsan lacus. Quis viverra nibh cras pulvinar mattis. Erat pellentesque adipiscing commodo elit at imperdiet dui accumsan. Felis donec et odio pellentesque diam volutpat commodo sed egestas. Quis risus sed vulputate odio ut enim blandit volutpat maecenas. Sit amet cursus sit amet dictum sit amet justo. Laoreet sit amet cursus sit amet dictum sit amet justo. Sed vulputate odio ut enim blandit volutpat. Eget mauris pharetra et ultrices neque ornare aenean. Purus in mollis nunc sed id semper risus.",

  "Risus at ultrices mi tempus imperdiet nulla malesuada pellentesque elit. Leo duis ut diam quam nulla. Quam viverra orci sagittis eu volutpat. Dapibus ultrices in iaculis nunc. Nulla pellentesque dignissim enim sit amet. Diam ut venenatis tellus in metus vulputate. Integer malesuada nunc vel risus commodo. Fringilla est ullamcorper eget nulla facilisi. In nulla posuere sollicitudin aliquam. Nec tincidunt praesent semper feugiat nibh sed pulvinar. Semper auctor neque vitae tempus quam pellentesque nec.",

  "Nisi scelerisque eu ultrices vitae auctor eu augue. Faucibus in ornare quam viverra orci sagittis eu volutpat odio. In vitae turpis massa sed elementum tempus egestas. Justo nec ultrices dui sapien. Egestas tellus rutrum tellus pellentesque eu tincidunt tortor. Eget lorem dolor sed viverra ipsum nunc aliquet bibendum enim. Sit amet porttitor eget dolor morbi non arcu risus quis. Lectus mauris ultrices eros in. Pellentesque habitant morbi tristique senectus et netus et malesuada. Sed adipiscing diam donec adipiscing tristique risus nec feugiat. Velit dignissim sodales ut eu sem integer vitae justo eget. Phasellus faucibus scelerisque eleifend donec pretium vulputate sapien nec sagittis. Ridiculus mus mauris vitae ultricies leo integer malesuada. Sed turpis tincidunt id aliquet risus. Quis auctor elit sed vulputate mi sit amet mauris commodo. Imperdiet proin fermentum leo vel orci. Ultrices gravida dictum fusce ut placerat orci. Eget sit amet tellus cras adipiscing enim eu turpis egestas. Et netus et malesuada fames ac turpis egestas.",

  "Ipsum dolor sit amet consectetur. Vestibulum lorem sed risus ultricies tristique nulla aliquet enim tortor. Congue mauris rhoncus aenean vel elit scelerisque. Felis eget velit aliquet sagittis id consectetur purus. Tortor at auctor urna nunc id cursus metus. Tortor posuere ac ut consequat. Lorem ipsum dolor sit amet consectetur adipiscing. Cursus turpis massa tincidunt dui ut ornare lectus sit amet. Egestas diam in arcu cursus euismod. Nisl condimentum id venenatis a. Cursus vitae congue mauris rhoncus aenean vel elit. Dui accumsan sit amet nulla facilisi morbi tempus. Faucibus interdum posuere lorem ipsum dolor sit. Feugiat sed lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi. Ipsum nunc aliquet bibendum enim facilisis gravida. Egestas diam in arcu cursus euismod quis. Lectus arcu bibendum at varius vel pharetra vel turpis nunc.",

  "Natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. At tellus at urna condimentum mattis. Pulvinar elementum integer enim neque volutpat ac tincidunt vitae semper. Fringilla phasellus faucibus scelerisque eleifend donec pretium. Sodales ut eu sem integer vitae. Libero volutpat sed cras ornare. Vitae purus faucibus ornare suspendisse sed nisi. Id ornare arcu odio ut sem nulla pharetra. Sed velit dignissim sodales ut eu. Eros in cursus turpis massa tincidunt. Amet dictum sit amet justo donec enim. Accumsan in nisl nisi scelerisque eu ultrices vitae auctor eu. Imperdiet dui accumsan sit amet nulla facilisi. Amet cursus sit amet dictum sit amet justo. Malesuada proin libero nunc consequat.",

  "Augue ut lectus arcu bibendum at varius vel pharetra vel. Egestas egestas fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate. Erat nam at lectus urna duis convallis. Id faucibus nisl tincidunt eget nullam non. Volutpat odio facilisis mauris sit. Pharetra pharetra massa massa ultricies. Sed blandit libero volutpat sed. Erat nam at lectus urna duis convallis convallis tellus. Mi tempus imperdiet nulla malesuada pellentesque elit eget. Porttitor rhoncus dolor purus non enim praesent. Bibendum ut tristique et egestas. Enim blandit volutpat maecenas volutpat blandit aliquam etiam erat velit. Magna eget est lorem ipsum. Elementum integer enim neque volutpat ac tincidunt vitae semper quis.",

  "Sed turpis tincidunt id aliquet risus feugiat in ante metus. Posuere urna nec tincidunt praesent. Ultricies mi eget mauris pharetra et ultrices neque ornare. Nisl condimentum id venenatis a condimentum. Adipiscing enim eu turpis egestas pretium. Nunc mi ipsum faucibus vitae aliquet. Lacinia at quis risus sed vulputate odio. Vestibulum lorem sed risus ultricies. Molestie a iaculis at erat. Non pulvinar neque laoreet suspendisse interdum. Interdum varius sit amet mattis vulputate enim nulla. At lectus urna duis convallis convallis tellus. Eget nulla facilisi etiam dignissim diam quis. Tellus elementum sagittis vitae et. Aliquam vestibulum morbi blandit cursus risus. At in tellus integer feugiat scelerisque varius morbi enim. Cum sociis natoque penatibus et. Porta lorem mollis aliquam ut porttitor.",

  "Malesuada fames ac turpis egestas maecenas pharetra convallis posuere morbi. Magna fringilla urna porttitor rhoncus dolor. Fames ac turpis egestas sed tempus urna et pharetra pharetra. Pellentesque massa placerat duis ultricies lacus sed turpis. Lectus urna duis convallis convallis tellus id interdum velit. Pretium viverra suspendisse potenti nullam ac tortor vitae. Adipiscing diam donec adipiscing tristique. Elit sed vulputate mi sit amet mauris commodo. Non arcu risus quis varius quam quisque. Et ligula ullamcorper malesuada proin. Suspendisse interdum consectetur libero id. Nullam vehicula ipsum a arcu cursus vitae congue mauris rhoncus. Varius duis at consectetur lorem donec massa sapien faucibus. Tellus at urna condimentum mattis pellentesque. Eros donec ac odio tempor orci dapibus ultrices in iaculis. Urna porttitor rhoncus dolor purus non enim praesent elementum. Venenatis a condimentum vitae sapien pellentesque habitant morbi tristique.",

  "Viverra vitae congue eu consequat. Dui accumsan sit amet nulla facilisi morbi tempus iaculis. Ut diam quam nulla porttitor massa id neque. Lacus suspendisse faucibus interdum posuere lorem ipsum dolor. Vulputate dignissim suspendisse in est ante. Lectus magna fringilla urna porttitor rhoncus dolor. Facilisis magna etiam tempor orci eu lobortis elementum nibh. Faucibus vitae aliquet nec ullamcorper sit. Consectetur adipiscing elit ut aliquam purus sit. Et molestie ac feugiat sed lectus. Ullamcorper dignissim cras tincidunt lobortis feugiat vivamus. Purus non enim praesent elementum facilisis leo vel.",

  "Interdum velit laoreet id donec ultrices. Sit amet nulla facilisi morbi tempus. A scelerisque purus semper eget duis at tellus at urna. Pellentesque nec nam aliquam sem et tortor consequat. Ut sem viverra aliquet eget sit amet. Tortor consequat id porta nibh venenatis cras sed felis. Nec ullamcorper sit amet risus. Fusce id velit ut tortor pretium viverra suspendisse potenti nullam. Morbi tristique senectus et netus et malesuada fames ac turpis. Neque convallis a cras semper auctor. Malesuada nunc vel risus commodo viverra maecenas accumsan lacus vel. Aliquet porttitor lacus luctus accumsan tortor posuere ac. Consectetur purus ut faucibus pulvinar elementum integer enim neque. Velit dignissim sodales ut eu sem integer vitae justo eget. Sagittis nisl rhoncus mattis rhoncus urna neque viverra justo nec.",
];

let button = document.querySelector("button");
let dummyTextField = document.querySelector("#dummy-text");

/* *************** */
/* WHEN PAGE LOADING */
/* *************** */
let randomIndex = Math.floor(Math.random() * dummyText.length);
dummyTextField.innerText = dummyText[randomIndex];

/* *************** */
/* FOR BUTTON CLICK */
/* *************** */
button.addEventListener("click", function () {
  let randomIndex = Math.floor(Math.random() * dummyText.length);

  dummyTextField.innerText = dummyText[randomIndex];
});
